name: 🛠️ CI - Build

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main

concurrency:
  group: ci-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    defaults:
        run:
          working-directory: ${{ github.workspace }}/frontend
    name: Build React
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.5.1
          cache: 'npm'
      - run: pwd
      - run: git branch
      - run: ls -l
      - run: npm clean-install
      - run: npm run lint
      - run: npm run build
