name: 🚀 CD - Release

permissions:
  contents: write

on:
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: cd-release
  cancel-in-progress: true

jobs:
  release:
    defaults:
      run:
        working-directory: ${{ github.workspace }}/frontend
    name: Build React
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.event.release.tag_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.5.1
          cache: 'npm'
      - run: pwd
      - run: ls -l
      - run: npm clean-install
      - run: npm run lint
      - run: npm run build
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Auto Release Bot"      
          git add dist/
          git commit -m "Release $TAG"
          git push